app            = "fantasy-league-api"
primary_region = "sin"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8080"
  CORS_ALLOWED_ORIGINS = "https://fantasy.adarw.xyz"

[http_service]
  internal_port        = 8080
  force_https          = true
  auto_stop_machines   = false
  auto_start_machines  = false
  min_machines_running = 1

[[vm]]
  size   = "shared-cpu-1x"
  memory = "256mb"
