package odds

// nameOverrides maps known Odds API team name variants to the canonical
// fantasy team name. Applied before any fuzzy matching logic.
var nameOverrides = map[string]string{
	// WCF
	"Algeria":              "Algeria",
	"Argentina":            "Argentina",
	"Australia":            "Australia",
	"Austria":              "Austria",
	"Belgium":              "Belgium",
	"Bosnia & Herzegovina": "Bosnia and Herzegovina",
	"Brazil":               "Brazil",
	"Canada":               "Canada",
	"Cape Verde":           "Cabo Verde",
	"Colombia":             "Colombia",
	"Croatia":              "Croatia",
	"Curaçao":              "Curaçao",
	"Czech Republic":       "Czechia",
	"DR Congo":             "Congo DR",
	"Ecuador":              "Ecuador",
	"Egypt":                "Egypt",
	"England":              "England",
	"France":               "France",
	"Germany":              "Germany",
	"Ghana":                "Ghana",
	"Haiti":                "Haiti",
	"Iran":                 "IR Iran",
	"Iraq":                 "Iraq",
	"Ivory Coast":          "Côte d'Ivoire",
	"Japan":                "Japan",
	"Jordan":               "Jordan",
	"Mexico":               "Mexico",
	"Morocco":              "Morocco",
	"Netherlands":          "Netherlands",
	"New Zealand":          "New Zealand",
	"Norway":               "Norway",
	"Panama":               "Panama",
	"Paraguay":             "Paraguay",
	"Portugal":             "Portugal",
	"Qatar":                "Qatar",
	"Saudi Arabia":         "Saudi Arabia",
	"Scotland":             "Scotland",
	"Senegal":              "Senegal",
	"South Africa":         "South Africa",
	"South Korea":          "Korea Republic",
	"Spain":                "Spain",
	"Sweden":               "Sweden",
	"Switzerland":          "Switzerland",
	"Tunisia":              "Tunisia",
	"Turkey":               "Türkiye",
	"Uruguay":              "Uruguay",
	"USA":                  "USA",
	"Uzbekistan":           "Uzbekistan",
}
